/**
 * The shape of `docs/design/design-system.manifest.json`, and the loader that checks a
 * parsed object against it.
 *
 * ## Why there is a loader at all
 *
 * The manifest is edited by hand by whoever is designing, and it is read by two blocking
 * gates. A field that is missing, misspelled or of the wrong type must stop the build with
 * the token's name in the message — not resolve to `undefined` and quietly take a default.
 * A gate that cannot read its input is failing open
 * [[a-gate-that-errors-is-failing-open]], and the most common way that happens is a
 * `?.` that silently skipped the thing it was supposed to check.
 *
 * ## Why not Zod
 *
 * `@irodora/contracts` owns the wire schemas, and this is not a wire type — nothing here
 * crosses a network boundary or reaches an API consumer. Pulling Zod in would put a runtime
 * dependency into a package that `apps/mobile` bundles, to validate a file that only exists
 * at build time. The validation is small enough to be explicit, and being explicit is what
 * lets each failure name the token it came from.
 */

/** The two themes. Both are checked independently; neither is derived from the other here. */
export const THEMES = ['dark', 'light'] as const;
export type Theme = (typeof THEMES)[number];

/**
 * What a token is *for*, which is what decides the contrast threshold it must meet.
 *
 * WCAG sets different minimums for text, large text and non-text (SC 1.4.3 and 1.4.11), so a
 * gate cannot check a pairing without knowing which of the three it is looking at. Guessing
 * would make the gate wrong in one direction or the other, silently.
 *
 * - `text` — 4.5:1. **The default**, so an omission fails safe: a token that forgets to
 *   declare its usage is held to the strictest requirement rather than the loosest.
 * - `largeText` — 3:1. Only legitimate at >= 18.66 px, or >= 24 px bold.
 * - `nonText` — 3:1. UI components, focus indicators, graphical objects.
 * - `surface` — imposes no requirement of its own. A background. It still participates in
 *   pairings; the requirement comes from the other side.
 */
export const USAGES = ['text', 'largeText', 'nonText', 'surface'] as const;
export type Usage = (typeof USAGES)[number];

/** OKLCh coordinates as the manifest states them. `alpha` present means translucent. */
export interface ManifestOklch {
  readonly l: number;
  readonly c: number;
  readonly h: number;
  readonly alpha?: number;
}

export interface ColorToken {
  readonly oklch: ManifestOklch;
  /**
   * DERIVED, never authored (ADR-0043). Regenerated by `pnpm --filter @irodora/design-tokens
   * generate`; a hand-edited value is a `contrast` gate failure.
   */
  readonly srgb: string;
  readonly role: string;
  readonly usage: Usage;
  /**
   * Declared contrast pairings. The gate checks these and only these — the cartesian product
   * would be fast to compute and meaningless to read. A pairing used in a component but
   * absent here is a gate failure once components exist (F-017).
   */
  readonly pairsWith: readonly string[];
  /**
   * For a translucent token: **every** ground it may legally sit on.
   *
   * An `rgba()` has no contrast ratio and no separation score until something is behind it,
   * so a translucent token must name its grounds or it cannot be checked at all. It is a
   * list rather than a single value because naming one ground lets the gate check the
   * favourable case: a black hairline over `surface.1` (white, in the light theme) is the
   * best it will ever look, and the same line divides rows on `surface.2` and frames the
   * `swatch.well`. The gate takes the **worst** ground, so a single favourable declaration
   * cannot launder a failure.
   */
  readonly compositeOver?: readonly string[];
  /**
   * Why this token is deliberately covered by no contrast pairing.
   *
   * Required when nothing — in either direction — names it, because gate scope is driven by
   * `pairsWith` and a token nobody names is checked by nothing while looking exactly like a
   * token that passed. This turns "unchecked" from an absence into a statement a reviewer
   * can disagree with.
   */
  readonly uncheckedReason?: string;
}

export interface StatusEntry {
  readonly colorToken: string;
  readonly iconToken: string;
  readonly textRequired: boolean;
}

export interface CvdPairs {
  readonly minSeparation: number;
  readonly pairs: readonly (readonly [string, string])[];
}

export interface ChromaException {
  readonly rule: 'chromaCeiling';
  readonly token: string;
  readonly reason: string;
  readonly owner: string;
  readonly recordedAt: string;
}

export interface ContrastGateConfig {
  readonly standard: string;
  readonly normalText: number;
  readonly largeText: number;
  readonly nonText: number;
  readonly reportAPCA: boolean;
  readonly blockingWhenStatus: string;
  readonly chromaCeiling: { readonly maxChroma: number };
}

export interface Manifest {
  readonly version: number;
  /** The approval lifecycle: `placeholder` makes the contrast gate report-only. */
  readonly status: string;
  readonly color: Readonly<Record<Theme, Readonly<Record<string, ColorToken>>>>;
  readonly statusPairing: Readonly<Record<string, StatusEntry>>;
  readonly cvdPairs: CvdPairs;
  readonly salience: Salience;
  readonly radius: Readonly<Record<string, number>>;
  readonly spacing: { readonly base: number; readonly scale: readonly number[] };
  readonly size: { readonly tapTarget: number };
  readonly exceptions: readonly ChromaException[];
  readonly gate: { readonly contrast: ContrastGateConfig };
}

/**
 * The RECORDED salience rank of the status tokens (F-067, ADR-0053).
 *
 * Recorded rather than inferred. A rank read back out of the values can never disagree with
 * them, and the defect this exists to catch was precisely that no order had been stated — the
 * dark theme ranked warn > ok > bad while light ranked bad > warn > ok, and nothing noticed.
 */
export interface Salience {
  /** Loudest first. Token names without a theme prefix; the rank must hold in EVERY theme. */
  readonly rank: readonly string[];
  readonly why: string;
}

/** Thrown with the path of the offending field. The path is the whole value of the message. */
export class ManifestError extends Error {
  constructor(path: string, detail: string) {
    super(`design-system.manifest.json: ${path} — ${detail}`);
    this.name = 'ManifestError';
  }
}

const isRecord = (v: unknown): v is Record<string, unknown> =>
  typeof v === 'object' && v !== null && !Array.isArray(v);

const isUsage = (v: string): v is Usage => (USAGES as readonly string[]).includes(v);

function requireRecord(v: unknown, path: string): Record<string, unknown> {
  if (!isRecord(v)) throw new ManifestError(path, 'expected an object');
  return v;
}

function requireNumber(v: unknown, path: string): number {
  if (typeof v !== 'number' || !Number.isFinite(v))
    throw new ManifestError(path, 'expected a finite number');
  return v;
}

function requireString(v: unknown, path: string): string {
  if (typeof v !== 'string' || v.length === 0)
    throw new ManifestError(path, 'expected a non-empty string');
  return v;
}

function parseOklch(v: unknown, path: string): ManifestOklch {
  const o = requireRecord(v, path);
  const l = requireNumber(o['l'], `${path}.l`);
  const c = requireNumber(o['c'], `${path}.c`);
  const h = requireNumber(o['h'], `${path}.h`);
  if (l < 0 || l > 1) throw new ManifestError(`${path}.l`, `OKLCh L is [0,1]; got ${String(l)}`);
  if (c < 0) throw new ManifestError(`${path}.c`, `chroma cannot be negative; got ${String(c)}`);
  if (o['alpha'] === undefined) return { l, c, h };
  const alpha = requireNumber(o['alpha'], `${path}.alpha`);
  if (alpha < 0 || alpha > 1)
    throw new ManifestError(`${path}.alpha`, `alpha is [0,1]; got ${String(alpha)}`);
  return { l, c, h, alpha };
}

function parseToken(v: unknown, path: string): ColorToken {
  const o = requireRecord(v, path);
  const oklch = parseOklch(o['oklch'], `${path}.oklch`);
  const srgb = requireString(o['srgb'], `${path}.srgb`);
  const role = requireString(o['role'], `${path}.role`);

  const usage: unknown = o['usage'];
  if (typeof usage !== 'string' || !isUsage(usage))
    throw new ManifestError(
      `${path}.usage`,
      `expected one of ${USAGES.join(', ')}; got ${JSON.stringify(usage)}. ` +
        'Without it the gate cannot know which WCAG minimum applies.',
    );

  const pairsWith = o['pairsWith'];
  if (!Array.isArray(pairsWith) || pairsWith.some((p) => typeof p !== 'string'))
    throw new ManifestError(`${path}.pairsWith`, 'expected an array of token names');

  // A translucent token without grounds is not evaluable: there is no ratio and no
  // separation score until something is behind it. Fail here rather than let a gate
  // silently skip it.
  const composite = o['compositeOver'];
  const hasGrounds =
    Array.isArray(composite) &&
    composite.length > 0 &&
    composite.every((g) => typeof g === 'string');
  if (oklch.alpha !== undefined && !hasGrounds)
    throw new ManifestError(
      `${path}.compositeOver`,
      'a translucent token must name every ground it may sit on, as a non-empty array, or ' +
        'neither its contrast nor its CVD separation is defined. Naming one favourable ' +
        'ground is how a check passes a token that is invisible where it is actually used.',
    );

  let token: ColorToken = {
    oklch,
    srgb,
    role,
    usage,
    pairsWith: pairsWith as readonly string[],
  };
  if (hasGrounds) token = { ...token, compositeOver: composite };
  if (o['uncheckedReason'] !== undefined)
    token = {
      ...token,
      uncheckedReason: requireString(o['uncheckedReason'], `${path}.uncheckedReason`),
    };
  return token;
}

/**
 * Validate a parsed manifest.
 *
 * Takes an already-parsed object rather than a path: reading a file is a Node concern, and
 * this package is bundled by `apps/mobile`. The one caller that touches the filesystem is
 * `generate.mjs`, which is not shipped.
 */
export function parseManifest(input: unknown): Manifest {
  const root = requireRecord(input, '<root>');

  const color = requireRecord(root['color'], 'color');
  const themes: Record<string, Record<string, ColorToken>> = {};
  for (const theme of THEMES) {
    const entry = requireRecord(color[theme], `color.${theme}`);
    const tokens: Record<string, ColorToken> = {};
    for (const [name, value] of Object.entries(entry))
      tokens[name] = parseToken(value, `color.${theme}.${name}`);
    themes[theme] = tokens;
  }

  // Every theme declares the same token names, or a component written against one theme
  // resolves to `undefined` in the other — at runtime, on whichever theme the author was
  // not looking at.
  const [first, ...rest] = THEMES;
  const reference = Object.keys(themes[first] ?? {}).sort();
  for (const theme of rest) {
    const names = Object.keys(themes[theme] ?? {}).sort();
    if (names.join(' ') !== reference.join(' ')) {
      const missing = reference.filter((n) => !names.includes(n));
      const extra = names.filter((n) => !reference.includes(n));
      throw new ManifestError(
        `color.${theme}`,
        `token names differ from color.${first}` +
          (missing.length > 0 ? `; missing ${missing.join(', ')}` : '') +
          (extra.length > 0 ? `; unexpected ${extra.join(', ')}` : ''),
      );
    }
  }

  // Every name in a pairsWith must resolve, in the theme that declared it.
  for (const theme of THEMES) {
    const tokens = themes[theme] ?? {};
    for (const [name, token] of Object.entries(tokens)) {
      for (const other of token.pairsWith)
        if (!(other in tokens))
          throw new ManifestError(
            `color.${theme}.${name}.pairsWith`,
            `"${other}" is not a token in this theme`,
          );
      for (const ground of token.compositeOver ?? [])
        if (!(ground in tokens))
          throw new ManifestError(
            `color.${theme}.${name}.compositeOver`,
            `"${ground}" is not a token in this theme`,
          );
    }
  }

  // `status` is the approval lifecycle, a string. The status/icon pairing lives under
  // `statusPairing` — the two were both spelled `status` until F-003, and JSON keeps only
  // the last key, so the approval value never survived parsing.
  const approvalStatus = requireString(root['status'], 'status');

  const statusRaw = requireRecord(root['statusPairing'], 'statusPairing');
  const statusEntries: Record<string, StatusEntry> = {};
  for (const [name, value] of Object.entries(statusRaw)) {
    if (name.startsWith('_')) continue;
    const o = requireRecord(value, `statusPairing.${name}`);
    const entry: StatusEntry = {
      colorToken: requireString(o['colorToken'], `statusPairing.${name}.colorToken`),
      iconToken: requireString(o['iconToken'], `statusPairing.${name}.iconToken`),
      textRequired: o['textRequired'] === true,
    };
    if (!entry.textRequired)
      throw new ManifestError(
        `statusPairing.${name}.textRequired`,
        'NFR-9: colour is never the only channel. A status that does not require text is ' +
          'a status expressible as colour alone.',
      );
    // The colour token must exist, or the pairing names a channel that does not render.
    for (const theme of THEMES)
      if (!(entry.colorToken in (themes[theme] ?? {})))
        throw new ManifestError(
          `statusPairing.${name}.colorToken`,
          `"${entry.colorToken}" is not a token in color.${theme}`,
        );
    statusEntries[name] = entry;
  }

  const cvdRaw = requireRecord(root['cvdPairs'], 'cvdPairs');
  const pairsRaw = cvdRaw['pairs'];
  if (!Array.isArray(pairsRaw)) throw new ManifestError('cvdPairs.pairs', 'expected an array');
  const pairs = pairsRaw.map((p, i): readonly [string, string] => {
    if (!Array.isArray(p) || p.length !== 2)
      throw new ManifestError(`cvdPairs.pairs[${String(i)}]`, 'expected a pair of token names');
    return [
      requireString(p[0], `cvdPairs.pairs[${String(i)}][0]`),
      requireString(p[1], `cvdPairs.pairs[${String(i)}][1]`),
    ] as const;
  });

  const salienceRaw = requireRecord(root['salience'], 'salience');
  const rankRaw = salienceRaw['rank'];
  if (!Array.isArray(rankRaw) || rankRaw.length < 2)
    throw new ManifestError('salience.rank', 'expected an array of at least two token names');
  const salience: Salience = {
    rank: rankRaw.map((r, i) => requireString(r, `salience.rank[${String(i)}]`)),
    why: requireString(salienceRaw['why'], 'salience.why'),
  };

  const gate = requireRecord(root['gate'], 'gate');
  const contrastRaw = requireRecord(gate['contrast'], 'gate.contrast');
  const ceiling = requireRecord(contrastRaw['chromaCeiling'], 'gate.contrast.chromaCeiling');

  const exceptionsRaw = root['exceptions'];
  if (!Array.isArray(exceptionsRaw)) throw new ManifestError('exceptions', 'expected an array');
  const exceptions = exceptionsRaw.map((e, i): ChromaException => {
    const o = requireRecord(e, `exceptions[${String(i)}]`);
    if (o['rule'] !== 'chromaCeiling')
      throw new ManifestError(
        `exceptions[${String(i)}].rule`,
        'the only recognised rule is chromaCeiling',
      );
    return {
      rule: 'chromaCeiling',
      token: requireString(o['token'], `exceptions[${String(i)}].token`),
      reason: requireString(o['reason'], `exceptions[${String(i)}].reason`),
      owner: requireString(o['owner'], `exceptions[${String(i)}].owner`),
      recordedAt: requireString(o['recordedAt'], `exceptions[${String(i)}].recordedAt`),
    };
  });

  const spacingRaw = requireRecord(root['spacing'], 'spacing');
  const scale = spacingRaw['scale'];
  if (!Array.isArray(scale) || scale.some((s) => typeof s !== 'number'))
    throw new ManifestError('spacing.scale', 'expected an array of numbers');

  const radiusRaw = requireRecord(root['radius'], 'radius');
  const radius: Record<string, number> = {};
  for (const [name, value] of Object.entries(radiusRaw)) {
    if (name.startsWith('_')) continue;
    radius[name] = requireNumber(value, `radius.${name}`);
  }
  if (radius['swatch'] !== 0)
    throw new ManifestError(
      'radius.swatch',
      'the swatch radius is 0 and does not change. A corner radius removes sampled area ' +
        'from exactly the region the eye uses to judge a flat colour.',
    );

  return {
    version: requireNumber(root['version'], 'version'),
    status: approvalStatus,
    color: themes as Manifest['color'],
    statusPairing: statusEntries,
    cvdPairs: {
      minSeparation: requireNumber(cvdRaw['minSeparation'], 'cvdPairs.minSeparation'),
      pairs,
    },
    salience,
    radius,
    spacing: { base: requireNumber(spacingRaw['base'], 'spacing.base'), scale: scale as number[] },
    size: {
      tapTarget: requireNumber(requireRecord(root['size'], 'size')['tapTarget'], 'size.tapTarget'),
    },
    exceptions,
    gate: {
      contrast: {
        standard: requireString(contrastRaw['standard'], 'gate.contrast.standard'),
        normalText: requireNumber(contrastRaw['normalText'], 'gate.contrast.normalText'),
        largeText: requireNumber(contrastRaw['largeText'], 'gate.contrast.largeText'),
        nonText: requireNumber(contrastRaw['nonText'], 'gate.contrast.nonText'),
        reportAPCA: contrastRaw['reportAPCA'] === true,
        blockingWhenStatus: requireString(
          contrastRaw['blockingWhenStatus'],
          'gate.contrast.blockingWhenStatus',
        ),
        chromaCeiling: {
          maxChroma: requireNumber(ceiling['maxChroma'], 'gate.contrast.chromaCeiling.maxChroma'),
        },
      },
    },
  };
}
