/**
 * The policy a device needs to check a theme it derived (F-154).
 *
 * ## Why this target exists
 *
 * A theme seeded by a platform accent cannot be verified when the manifest is compiled — the
 * seed does not exist until the app is running. So the contrast and CVD checks run on the
 * phone, and the phone therefore needs **the policy**: the declared pairings, the floors, the
 * CVD pairs, the salience rank, the chroma ceiling, the exceptions.
 *
 * It does not need the type scale, the motion durations, the elevation table, or the prose. The
 * `role` on every token is a paragraph explaining a decision to a reader, and there is no reader
 * on a phone — so it is emitted empty. Trimmed this way the value is about 11 KB rather than 36.
 *
 * ## Only the authored pair
 *
 * The derived families are computed from these two by the same function the device uses, so
 * shipping all eight would be shipping six palettes the device can rebuild — and it is the base
 * that a seeded theme is derived FROM.
 *
 * ## What keeps it from drifting
 *
 * `CheckableManifest` is the argument type of the same `checkContrast` and `checkSeparation` the
 * gate calls. The gate passes the real manifest, the device passes this. Two callers, one set of
 * functions — a second implementation is the thing this arrangement exists to avoid.
 */

import { BASE_THEMES, type ColorToken, type Manifest } from '../manifest.js';

/** Prose a phone has no reader for. Emitted empty rather than dropped, so the shape holds. */
function trim(token: ColorToken): ColorToken {
  return {
    ...token,
    role: '',
    ...(token.uncheckedReason === undefined ? {} : { uncheckedReason: '' }),
  };
}

export function emitRuntime(manifest: Manifest): string {
  const color: Record<string, Record<string, ColorToken>> = {};
  for (const mode of BASE_THEMES) {
    const tokens: Record<string, ColorToken> = {};
    for (const [name, token] of Object.entries(manifest.color[mode])) tokens[name] = trim(token);
    color[mode] = tokens;
  }

  const payload = {
    color,
    gate: manifest.gate,
    cvdPairs: manifest.cvdPairs,
    salience: manifest.salience,
    statusPairing: manifest.statusPairing,
    exceptions: manifest.exceptions,
  };

  return [
    '/* eslint-disable */',
    '// prettier-ignore',
    '/**',
    ' * GENERATED by `node scripts/generate-design-tokens.mjs`. Do not edit.',
    ' *',
    ' * The policy a device needs to check a theme it derived at runtime (F-154) — the declared',
    ' * pairings, the contrast floors, the CVD pairs, the salience rank, the chroma ceiling and the',
    ' * exceptions, plus the two AUTHORED palettes a seeded theme is derived from.',
    ' *',
    ' * Not the type scale, the motion table or the prose: `role` is a paragraph for a reader and',
    ' * there is no reader on a phone.',
    ' *',
    ' * It is passed to the SAME `checkContrast` and `checkSeparation` the gate calls. That is what',
    ' * stops the device and CI from disagreeing about what passes.',
    ' */',
    '',
    "import type { CheckableManifest } from '../check.js';",
    '',
    `export const runtimeManifest: CheckableManifest = ${JSON.stringify(payload, null, 2)};`,
    '',
  ].join('\n');
}
