/**
 * Metro, with Uniwind's transformer (ADR-0062).
 *
 * **This is where HeroUI's styling actually happens**, and knowing that is the difference
 * between a passing gate and a passing gate that measures nothing. Uniwind resolves every
 * `className` here, at bundle time. Jest does not run Metro, so a component styled only
 * through `className` renders in the test harness with no colours in its tree at all
 * [[a-style-engine-that-resolves-in-metro-is-invisible-to-jest]].
 *
 * That is why `@irodora/ui` passes colour through the `style` prop and never through a
 * utility class, and why lint and the conformance suite both enforce it.
 *
 * CommonJS rather than ESM: Metro loads this file with `require`, and the rest of the
 * repository being `"type": "module"` is why the extension is `.js` under an explicit
 * `module.exports` rather than `metro.config.mjs`.
 */

const { getDefaultConfig } = require('expo/metro-config');
const { withUniwindConfig } = require('uniwind/metro');
const { wrapWithReanimatedMetroConfig } = require('react-native-reanimated/metro-config');

const config = getDefaultConfig(__dirname);

/*
 * `unstable_enablePackageExports` — heroui-native's `react-native` export condition points at
 * its TypeScript SOURCE rather than its build, which is how it stays styleable by Uniwind's
 * transformer. Metro needs package exports on to see that condition at all.
 */
config.resolver.unstable_enablePackageExports = true;

module.exports = withUniwindConfig(wrapWithReanimatedMetroConfig(config), {
  cssEntryFile: './global.css',
  // GENERATED by `pnpm --filter @irodora/design-tokens generate`, from the manifest. Editing
  // it by hand is editing a build artefact; the token values live in
  // `docs/design/design-system.manifest.json`.
  dtsFile: './src/uniwind.d.ts',
});
