import { withAppBuildGradle, type ConfigPlugin } from '@expo/config-plugins';

/**
 * The release signing configuration, injected into the generated Android project.
 *
 * ## Why a config plugin rather than an edit
 *
 * `android/` is generated by `expo prebuild` and is gitignored. Hand-editing it is forbidden
 * by [`../AGENTS.md`](../AGENTS.md) and the reason is not style: the edit disappears on the
 * next prebuild, silently, and the build that follows is signed with the debug key while
 * still being called `release`. A config plugin is the only mechanism that survives
 * regeneration, so it is the only honest place for this.
 *
 * ## What the React Native template ships, and why it cannot stand
 *
 * ```groovy
 * release {
 *     // Caution! In production, you need to generate your own keystore file.
 *     signingConfig signingConfigs.debug
 * }
 * ```
 *
 * The debug keystore is checked into every React Native project on earth with the password
 * `android`. An artefact signed with it is installable by anyone and attributable to nobody,
 * and — because Android identifies an app by *package id plus signing certificate* — shipping
 * one to a real person means no properly signed build can ever update it. That is not a
 * warning to read and move past; it is the single most consequential default in the template.
 *
 * ## The failure mode this file is built around
 *
 * If the environment carries no keystore, the injected `release` config simply has no
 * `storeFile`, and AGP fails the release packaging task. **It never falls back to debug.**
 * Debug builds are untouched, which is what keeps the on-demand test-build lane working with
 * no secrets at all.
 *
 * The other failure mode is an Expo or React Native upgrade changing the template text under
 * us. Then the anchors below are not found — and this throws, loudly, at prebuild time.
 * Returning the file unchanged would be the quiet version of exactly the disaster above.
 *
 * @see docs/adr/0058-release-builds-are-github-actions-and-gradle-not-eas.md
 * @see docs/operations/signing-and-credentials.md
 */

/** Where the container of signing configurations opens. */
const SIGNING_CONFIGS_ANCHOR = '    signingConfigs {\n';

/** The template's release build type, verbatim, including the comment it ships with. */
const DEBUG_SIGNED_RELEASE_ANCHOR = `        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug`;

const RELEASE_SIGNING_CONFIG = `        // Irodora — the release key, read from the environment at build time (F-080).
        // Written by apps/mobile/plugins/withReleaseSigning.ts; never edit android/ by hand.
        //
        // With no IRODORA_ANDROID_KEYSTORE_PATH there is no storeFile, so AGP fails the
        // release packaging task. That is deliberate: the alternative is a release-labelled
        // artefact signed with a key every machine in the world already has. Debug builds do
        // not read this block and keep working with no secrets present.
        //
        // v1 (JAR) signing is OFF: minSdk is 24, every supported device understands v2, and
        // v1 is what the Janus vulnerability attacked.
        release {
            def irodoraKeystore = System.getenv("IRODORA_ANDROID_KEYSTORE_PATH")
            if (irodoraKeystore) {
                storeFile file(irodoraKeystore)
                storePassword System.getenv("IRODORA_ANDROID_KEYSTORE_PASSWORD")
                keyAlias System.getenv("IRODORA_ANDROID_KEY_ALIAS")
                keyPassword System.getenv("IRODORA_ANDROID_KEY_PASSWORD")
            }
            enableV1Signing false
            enableV2Signing true
            enableV3Signing true
            enableV4Signing false
        }
`;

// The comment deliberately does NOT name the debug config: `release-signing.test.ts` asserts
// that the whole release build type is free of that literal, and a test that has to special-case
// comments is a weaker test than one that can read the block as text.
const RELEASE_BUILD_TYPE = `        release {
            // Irodora: signed with the release key — see plugins/withReleaseSigning.ts.
            signingConfig signingConfigs.release`;

/** How many times `needle` occurs in `haystack`. */
function countOccurrences(haystack: string, needle: string): number {
  let count = 0;
  let at = haystack.indexOf(needle);
  while (at !== -1) {
    count++;
    at = haystack.indexOf(needle, at + needle.length);
  }
  return count;
}

/**
 * Rewrite `app/build.gradle` so `release` is signed with the release key.
 *
 * Exported and pure so it can be tested against the real template text without running a
 * prebuild — and so the throwing cases can be tested at all.
 *
 * @throws if either anchor is missing or ambiguous, or if the transform has already run.
 */
export function addReleaseSigning(buildGradle: string): string {
  if (buildGradle.includes('signingConfig signingConfigs.release'))
    throw new Error(
      'withReleaseSigning: build.gradle already references signingConfigs.release. Applying ' +
        'twice would nest the config or duplicate it; run `expo prebuild --clean` instead of ' +
        'layering onto a stale native project.',
    );

  for (const [label, anchor] of [
    ['signingConfigs {', SIGNING_CONFIGS_ANCHOR],
    ['the debug-signed release build type', DEBUG_SIGNED_RELEASE_ANCHOR],
  ] as const) {
    const found = countOccurrences(buildGradle, anchor);
    if (found !== 1)
      throw new Error(
        `withReleaseSigning: expected exactly one "${label}" in app/build.gradle, found ${String(found)}. ` +
          'The React Native template has changed. Do NOT loosen this match — a transform that ' +
          'silently does nothing leaves the release build signed with the debug key, which is ' +
          'the exact outcome this plugin exists to prevent. Re-derive the anchor from the new ' +
          'template and update apps/mobile/test/release-signing.test.ts with it.',
      );
  }

  return buildGradle
    .replace(SIGNING_CONFIGS_ANCHOR, SIGNING_CONFIGS_ANCHOR + RELEASE_SIGNING_CONFIG)
    .replace(DEBUG_SIGNED_RELEASE_ANCHOR, RELEASE_BUILD_TYPE);
}

const withReleaseSigning: ConfigPlugin = (config) =>
  withAppBuildGradle(config, (mod) => {
    if (mod.modResults.language !== 'groovy')
      throw new Error(
        `withReleaseSigning: app/build.gradle is ${mod.modResults.language}, not groovy. ` +
          'The anchors are Groovy text and would not match.',
      );
    mod.modResults.contents = addReleaseSigning(mod.modResults.contents);
    return mod;
  });

export default withReleaseSigning;
